add_rules("mode.debug", "mode.release")

set_project("nav_test")
set_targetdir("$(projectdir)/bin/test")
set_objectdir("$(projectdir)/libs/test")
set_languages("c++23", "c11")
set_toolchains("gcc")
set_toolset("cc", "gcc-14")
set_toolset("cxx", "g++-14")

target("test")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_cxxflags("-fpie")
    add_deps("nav_core")
    add_files("test.cpp")
target_end()

target("test_time")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_deps("nav_core")
    add_files("test_time.cpp")
target_end()

target("space_test")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_deps("nav_core","rtklib")
    add_files("space_test.cpp")
target_end()

target("filter_test")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_deps("nav_core")
    add_files("filter_test.cpp")
target_end()

target("utils_test")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_deps("nav_core")
    add_files("test_utils.cpp")
target_end()

target("test_option")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_includedirs("$(projectdir)/src/core/include")
    add_packages("cpptrace")
    add_files("test_option.cpp")
target_end()

target("test_result")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_includedirs("$(projectdir)/src/core/include")
    add_packages("cpptrace")
    add_files("test_result.cpp")
target_end()

target("test_gnss_brdc_ephemeris")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_files("gnss/brdc_ephemeris.cpp")
    add_deps("nav_core")
target_end()

target("test_gnss_combine_obs")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_files("gnss/combine_obs.cpp")
    add_deps("nav_core","plot")
target_end()

target("test_config")
    set_kind("binary")
    set_languages("c++23")
    set_pcheader("doctest.h")
    add_files("test_config.cpp")
    add_deps("nav_core")
    add_packages("cpptrace")
target_end()

target("test_exprtk")
    set_kind("binary")
    set_languages("c++23")
    add_files("test_exprtk.cpp")
    add_deps("exprtk")
target_end()