[meta]
task = "rtk"
project = "rtk-fgo-test"
executor = "mashuo"
time = "2024-11-20 11:20:00"


[solution]
# solution mode 
#   NONE = 0,
#   FIXED = 1,
#   FLOAT = 2,
#   SBAS = 3,
#   DGPS = 4,
#   SINGLE = 5,
#   PPP = 6,
#   DR_LOOSE = 7,
#   DR_TIGHT = 8,
#   FGO = 9,
mode = 9
base = "base001" 
rover = "default"

[output]
path = "../output/"


[filter]
