[meta]
task = "spp"
project = "spp-test"
executor = "mashuo"
time = "2024-11-20 11:20:00"

[io]
rover_nav_path = [
    "/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01.nav",
    "/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01.21N",
]
rover_obs_path = "/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01-GPS&BDS-Double.obs"
out_path = "/root/project/nav_cxx/test_resources/SPP/result.pos"
rover_ref_pos = [-2267804.5263, 5009342.3723, 3220991.8632]

[model]
trop = 0
iono = 0

[filter]
