filters = [ '=GPS', '>=2023-10-11 20:08:03' ]
minimum_elevation = 10.0
minimum_snr = 30.0
navigation_files_path = [
    '/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01.nav',
    '/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01.21N'
]
observation_path = '/root/project/nav_cxx/test_resources/SPP/NovatelOEM20211114-01.obs'
output_path = '/root/project/nav_cxx/test_resources/SPP/res.txt'